### ISSUE TITLE
Question about Two-stage Interactive Generation

### ISSUE THREAD

**Issue by MING-ZCH** [27182812/LLM4ED#1]
hi, congratulations on your article being accepted by EMNLP!
我有一些这篇工作中“Two-stage Interactive Generation”的问题还望解答：
1. 该策略是否是以文中提及的prompt形式，使用在Guideline Instruction中？有无具体prompt的参考示例
2. 有关model’s thought process是否只是隐式体现在模型输出过程，有无显式表现？
![image](https://github.com/27182812/LLM4ED/assets/119648793/1e0a40f8-1ef3-4a4a-b1ed-5a28c2a5899c)
Best wishes~

**Comment by 27182812** [comment]
您好，感谢你对我们工作的关注。
关于Q1，表7是一个概括式的prompt模版格式，“Two-stage Interactive Generation”生成的具体prompt可以参考https://github.com/27182812/LLM4ED/blob/main/prompt_twostages.py
关于Q2，第一阶段模型的输出，是对上文用户可能经历的情感和情境进行的推测，是显式的，第二阶段模型的输出是最终的回复，是对思考过程的隐式体现

**Comment by MING-ZCH** [comment]
thanks！

**Comment by pareshgami** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
unixfile, @Naclazzy, @edydkim, @lukkonior, @zeqing-guo, @ferrarif1, @Nazar2, @chengdong0421, @andreytrifonov, @osamaawanpk, @ASchmidt1024, @beijinggao, @cruboy, @leonkong, @Synaxis, @toonme, @calder, @digiront, @adnils, @hudaweiv, @BennyKok, @keni7385, @castle321, @conniechao, @tequillasun, @johnjelinek, @xdark21, @monkey0722, @ksallberg, @alonsomao, @troyjfarrell, @yalu, @ChristopherWen, @drobati, @nrnaveen, @overgear, @aviler, @doskey, @amitpdev, @zyan0, @crypto-ali, @mestar99, @timnugent, @netindev, @manuasir, @ZGQ-inc, @markus1540, @ijpq, @creachang, @flacks

**Comment by diegoreis1980** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
crookworm, @starfishspider, @PaulDesprairies, @msammarco, @Tranquil-Flow, @RodeRickIsWatching, @adamegyed, @z156854666, @modjoules, @AnthonyAkentiev, @Fenricage, @firstfu, @helderjnpinto, @chriswg, @one-n-dunn, @akcgjc007, @hehe2046, @ryuichi1208, @Totsamji13, @mixass, @PaddyMc, @billyledev, @mengmengmengqiang, @Casslin, @JasonFengGit, @zero1ne, @makss68, @aroncds, @ssssdl, @gaetanlegac, @Antoniaiaiaiaia, @w72, @pcaversaccio, @syphrpunk, @chabroA, @Tianranxu, @TerryThreatt, @freesnow, @v479038280, @Peaches0303, @geekchu, @hisergiorojas, @Dhanushdhaari, @Catherinesjkim, @gw3218, @AaricChen, @stplaydog, @amy-jung, @avalverdero, @imektasingh

**Comment by Synaxis** [comment]
Congrats

**Comment by manuasir** [comment]
The link seems broken.
