### ISSUE TITLE
关于评价指标的问题

### ISSUE THREAD

**Issue by Yuzi0123** [27182812/LLM4ED#2]
作者您好！
想请教一下怎么复现自动评估中的BERTscore、BLEU-n和Acc？
在evaluate.py中只有distinct的相关代码。
期待您的解答！

**Comment by 27182812** [comment]
您好，感谢对我们工作的关注。
BERTScore采用原作者提供的代码[bert_score](https://github.com/Tiiiger/bert_score)进行评测，BLEU-n评测采用了公开NLG评测工具库[nlg-eval](https://github.com/Maluuba/nlg-eval)，Acc的实现很简单，模型预测的情感类别和实际情感类别一致的比例。
